"""Initial migration

Revision ID: 8023962463ae
Revises: 
Create Date: 2025-10-31 05:41:01.028121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8023962463ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('geometry', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('raw_rainfall', sa.Float(), nullable=True),
    sa.Column('raw_ndvi', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['data_cell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_calc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('flood_index', sa.Float(), nullable=True),
    sa.Column('drought_index', sa.Float(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['timeseries_id'], ['time_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('hazard_type', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('issue_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['index_calc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_recipient',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
    sa.PrimaryKeyConstraint('alert_id', 'recipient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_recipient')
    op.drop_table('alert')
    op.drop_table('index_calc')
    op.drop_table('time_series')
    op.drop_table('data_cell')
    op.drop_table('region')
    op.drop_table('recipient')
    # ### end Alembic commands ###
